import React from 'react';
export const metadata = {
  title: "Appointment | Lawyer",
  description: "Generated by create next app",
};
const Services = () => {
  return (
    <div>
      Appointments
    </div>
  );
};

export default Services;