import Signup from '@/Components/Signup';
import React from 'react';
export const metadata = {
  title: "Register | Lawyer",
  description: "Generated by create next app",
};
const Register = () => {
  return (
    <div>
      <Signup/>
    </div>
  );
};

export default Register;