import AppointmentCard from "@/Components/AppointmentCard";
import LawyerCard from "@/Components/LawyerCard";
import Banner from "@/Components/Banner";
import PrimaryButton from "@/Components/PrimaryButton";


export const metadata = {
  title: "Home | Lawyer",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
     <section className="my-5">
        <Banner />
      </section>
      <LawyerCard/>
      <div className="p-10">hello</div>
      <AppointmentCard />
      <div className="p-10">hello</div>
      {/* <PrimaryButton link="/contact">Click</PrimaryButton> */}
    </div>
  );
}
