
import AppointmentCard from "@/Components/AppointmentCard";
import LawyerCard from "@/Components/LawyerCard";
import Banner from "@/Components/Banner";

export const metadata = {
  title: "Home | Lawyer",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
     <section className="my-5">
        <Banner />
      </section>
      <LawyerCard/>
      <AppointmentCard/>
      <div>hello</div>
    </div>
  );
}
