import AppointmentCard from "@/Components/AppointmentCard";
import LawyerCard from "@/Components/LawyerCard";

export const metadata = {
  title: "Home | Layer",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <LawyerCard/>
      <AppointmentCard/>
  </div>
  )
}
